# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f42016641512fdb4fa62d3f2a559682c6a1b95a1bf2d8cdf77f73beb9e8a59921215a520784cf1b75262c138ec67f1811667fa7c5fc18500c4ec9b7b58391527

test:
  secret_key_base: dc6e58425c8c6f93b8775fc9f5db4c24edfed1d951556ee291c0357f280c825ea4064ddd83baa22d1f1e3ee0a06e648deef67ae781f7e37757751311d24c96a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
